baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-gb"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Lindsay Lovers"
  subtitle    = "Here are the facts or an approximation of them.."
  copyright   = "Â© 2020"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"
  linkedinName = "eueung"
  mediumName = ""

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "GL"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95
